### ISSUE TITLE
Fix Error with Google Authentification in CI

### ISSUE THREAD

**Issue by RagdollGoDown** [PlateSwipe/PlateSwipe#181]
When running test on the CI, there is an error linked to the Google authentification. We previously tried to get rid of it through changing the signin system, but it seems the issue is deep in the CI.

**Comment by Ylanv** [comment]
The issue stemmed from how the APK was signed in different environments. When using `gradle assembleDebug` in Android Studio, the APK is automatically signed with a key whose SHA-1 fingerprint matches the one displayed by the Gradle `signingReport`. This SHA-1 fingerprint is what each team member registered with Firebase. However, when GitHub Actions runs `assembleDebug`, it appears to use a different key, which prevented Firebase connections from working as expected.

To resolve this, I created a dedicated keystore with the correct SHA-1 registered in Firebase. By signing the APK with this keystore, Firebase authentication works as intended, allowing users to connect seamlessly. 

Special thanks to @RagdollGoDown and @AdriB02 for their valuable contributions to the troubleshooting process. Their efforts in exploring possible solutions and investigating the Firebase configuration were instrumental in helping us identify the root cause and implement a successful fix.
